# YOU SHOULD EDIT ABOVE PROPS

HOST = "example.com"  # DOMAIN OR IP
TG_TOKEN = "1112223334:AABBCCDDZy7uogv5XhjLLXL1HHJEVAA1212"  # TELEGRAM TOKEN
TG_CHAT_ID = "123456562"  # YOUR CHAT ID WITH BOT

# IF YOU WANT YOU CAN CHANGE TG MESSAGE
# VAR datetime IT IS CURENT DATE TIME IN VIEW "HH:MM:SS | YYYY.MM.DD"
# VAR host IT IS HOST VARIABLE

PROBLEM_MESSAGE: str = """
❌  MASTER PROBLEM  ❌
TIME: {datetime}
HOST: ZABBIX MASTER SERVER - {host}
TRIGGER: Unavailable by ICMP
LEVEL: DISASTER
"""

RESOLVE_MESSAGE: str = """
✅ RESOLVED ✅
TIME: {datetime}
HOST: ZABBIX MASTER SERVER - {host}
TRIGGER: Unavailable by ICMP
"""